// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'search-button': string;
  'searchButton': string;
}
export const cssExports: CssExports;
export default cssExports;
