// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error-message': string;
  'errorMessage': string;
}
export const cssExports: CssExports;
export default cssExports;
