// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inner-wrapper': string;
  'innerWrapper': string;
  'main-weather-wrapper': string;
  'mainWeatherWrapper': string;
  'results-wrapper': string;
  'resultsWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
