// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'date-time': string;
  'dateTime': string;
  'header': string;
  'history-item-icon': string;
  'historyItemIcon': string;
  'list-item': string;
  'list-item-inner-wrapper': string;
  'listItem': string;
  'listItemInnerWrapper': string;
  'remove-button': string;
  'removeButton': string;
  'search-history-panel': string;
  'searchHistoryPanel': string;
}
export const cssExports: CssExports;
export default cssExports;
