// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'city-name': string;
  'cityName': string;
  'country': string;
  'details-wrapper': string;
  'detailsWrapper': string;
  'icon-wrapper': string;
  'iconWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
