export const ADD_TO_SEARCH_HISTORY = 'ADD_TO_SEARCH_HISTORY';
export const START_ADD_TO_SEARCH_HISTORY = 'START_ADD_TO_SEARCH_HISTORY';
export const END_ADD_TO_SEARCH_HISTORY = 'END_ADD_TO_SEARCH_HISTORY';
export const REMOVE_ITEM_FROM_HISTORY = 'REMOVE_ITEM_FROM_HISTORY';
export const END_REMOVE_ITEM_FROM_HISTORY = 'END_REMOVE_ITEM_FROM_HISTORY';

export const SET_WEATHER = 'SET_WEATHER';
export const HISTORY_LIST_SAVED_INTO_LOCAL_STORAGE = 'HISTORY_LIST_SAVED_INTO_LOCAL_STORAGE';
export const START_FETCH_WEATHER = 'START_FETCH_WEATHER';

export const END_FETCH_WEATHER = 'END_FETCH_WEATHER';

export const SET_TEMP_TYPE = 'SET_TEMP_TYPE';
export const API = 'API';
