// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main-header': string;
  'mainHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
