// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-wrapper': string;
  'buttonWrapper': string;
  'search-box-wrapper': string;
  'searchBoxWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
