// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'radio-button': string;
  'radioButton': string;
}
export const cssExports: CssExports;
export default cssExports;
