// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dark-theme': string;
  'darkTheme': string;
  'default-theme': string;
  'defaultTheme': string;
  'root-dark-theme': string;
  'root-default-theme': string;
  'rootDarkTheme': string;
  'rootDefaultTheme': string;
}
export const cssExports: CssExports;
export default cssExports;
